/*
 * generated by Xtext 2.27.0.M3
 */
package eu.fbk.se.mathexpeditor.ui;

import com.google.inject.Injector;
import eu.fbk.se.mathexpeditor.ui.internal.MathexpeditorActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MExpExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(MathexpeditorActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		MathexpeditorActivator activator = MathexpeditorActivator.getInstance();
		return activator != null ? activator.getInjector(MathexpeditorActivator.EU_FBK_SE_MATHEXPEDITOR_MEXP) : null;
	}

}
