/*
 * generated by Xtext 2.27.0.M3
 */
package eu.fbk.se.mathexpeditor.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractMExpValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(eu.fbk.se.mathexpeditor.mExp.MExpPackage.eINSTANCE);
		return result;
	}
}
