/*
 * generated by Xtext 2.27.0.M3
 */
package eu.fbk.se.mathexpeditor;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MExpStandaloneSetup extends MExpStandaloneSetupGenerated {

	public static void doSetup() {
		new MExpStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
