/*
 * generated by Xtext 2.27.0.M3
 */
package eu.fbk.se.mathexpeditor;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MExpRuntimeModule extends AbstractMExpRuntimeModule {
}
