/**
 * generated by Xtext 2.27.0
 */
package eu.fbk.se.mathexpeditor.mExp;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link eu.fbk.se.mathexpeditor.mExp.Model#getConstDefinitions <em>Const Definitions</em>}</li>
 *   <li>{@link eu.fbk.se.mathexpeditor.mExp.Model#getVarDefinitions <em>Var Definitions</em>}</li>
 *   <li>{@link eu.fbk.se.mathexpeditor.mExp.Model#getExpDefinitions <em>Exp Definitions</em>}</li>
 * </ul>
 *
 * @see eu.fbk.se.mathexpeditor.mExp.MExpPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Const Definitions</b></em>' containment reference list.
   * The list contents are of type {@link eu.fbk.se.mathexpeditor.mExp.ConstDefinition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Const Definitions</em>' containment reference list.
   * @see eu.fbk.se.mathexpeditor.mExp.MExpPackage#getModel_ConstDefinitions()
   * @model containment="true"
   * @generated
   */
  EList<ConstDefinition> getConstDefinitions();

  /**
   * Returns the value of the '<em><b>Var Definitions</b></em>' containment reference list.
   * The list contents are of type {@link eu.fbk.se.mathexpeditor.mExp.VarDefinition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Definitions</em>' containment reference list.
   * @see eu.fbk.se.mathexpeditor.mExp.MExpPackage#getModel_VarDefinitions()
   * @model containment="true"
   * @generated
   */
  EList<VarDefinition> getVarDefinitions();

  /**
   * Returns the value of the '<em><b>Exp Definitions</b></em>' containment reference list.
   * The list contents are of type {@link eu.fbk.se.mathexpeditor.mExp.ExpDefinition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp Definitions</em>' containment reference list.
   * @see eu.fbk.se.mathexpeditor.mExp.MExpPackage#getModel_ExpDefinitions()
   * @model containment="true"
   * @generated
   */
  EList<ExpDefinition> getExpDefinitions();

} // Model
