/*
 * generated by Xtext 2.27.0.M3
 */
package eu.fbk.se.mathexpeditor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MExpUiModule extends AbstractMExpUiModule {

	public MExpUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
