/**
 * generated by Xtext 2.27.0
 */
package eu.fbk.se.mathexpeditor.mExp.impl;

import eu.fbk.se.mathexpeditor.mExp.ConstDefinition;
import eu.fbk.se.mathexpeditor.mExp.MExpPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Const Definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link eu.fbk.se.mathexpeditor.mExp.impl.ConstDefinitionImpl#getVarName <em>Var Name</em>}</li>
 *   <li>{@link eu.fbk.se.mathexpeditor.mExp.impl.ConstDefinitionImpl#getVarValue <em>Var Value</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ConstDefinitionImpl extends MinimalEObjectImpl.Container implements ConstDefinition
{
  /**
   * The default value of the '{@link #getVarName() <em>Var Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarName()
   * @generated
   * @ordered
   */
  protected static final String VAR_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVarName() <em>Var Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarName()
   * @generated
   * @ordered
   */
  protected String varName = VAR_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getVarValue() <em>Var Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarValue()
   * @generated
   * @ordered
   */
  protected static final int VAR_VALUE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getVarValue() <em>Var Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVarValue()
   * @generated
   * @ordered
   */
  protected int varValue = VAR_VALUE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConstDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MExpPackage.Literals.CONST_DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVarName()
  {
    return varName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVarName(String newVarName)
  {
    String oldVarName = varName;
    varName = newVarName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MExpPackage.CONST_DEFINITION__VAR_NAME, oldVarName, varName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getVarValue()
  {
    return varValue;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVarValue(int newVarValue)
  {
    int oldVarValue = varValue;
    varValue = newVarValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MExpPackage.CONST_DEFINITION__VAR_VALUE, oldVarValue, varValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MExpPackage.CONST_DEFINITION__VAR_NAME:
        return getVarName();
      case MExpPackage.CONST_DEFINITION__VAR_VALUE:
        return getVarValue();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MExpPackage.CONST_DEFINITION__VAR_NAME:
        setVarName((String)newValue);
        return;
      case MExpPackage.CONST_DEFINITION__VAR_VALUE:
        setVarValue((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MExpPackage.CONST_DEFINITION__VAR_NAME:
        setVarName(VAR_NAME_EDEFAULT);
        return;
      case MExpPackage.CONST_DEFINITION__VAR_VALUE:
        setVarValue(VAR_VALUE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MExpPackage.CONST_DEFINITION__VAR_NAME:
        return VAR_NAME_EDEFAULT == null ? varName != null : !VAR_NAME_EDEFAULT.equals(varName);
      case MExpPackage.CONST_DEFINITION__VAR_VALUE:
        return varValue != VAR_VALUE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (varName: ");
    result.append(varName);
    result.append(", varValue: ");
    result.append(varValue);
    result.append(')');
    return result.toString();
  }

} //ConstDefinitionImpl
