/*
 * generated by Xtext 2.27.0.M3
 */
package eu.fbk.se.mathexpeditor.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import eu.fbk.se.mathexpeditor.MExpRuntimeModule;
import eu.fbk.se.mathexpeditor.MExpStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MExpIdeSetup extends MExpStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MExpRuntimeModule(), new MExpIdeModule()));
	}
	
}
