/*
 * generated by Xtext 2.27.0.M3
 */
package eu.fbk.se.mathexpeditor.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MExpAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("eu/fbk/se/mathexpeditor/parser/antlr/internal/InternalMExp.tokens");
	}
}
