/*
 * generated by Xtext 2.27.0.M3
 */
package eu.fbk.se.mathexpeditor.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class MExpScopeProvider extends AbstractMExpScopeProvider {

}
