/*
 * generated by Xtext 2.27.0.M3
 */
package eu.fbk.se.mathexpeditor.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMExpScopeProvider extends DelegatingScopeProvider {
}
